spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://2c:5555/super-jacoco?serverTimezone=Asia/Shanghai&useSSL=true
    username: spider
    password: dB&x(oNt1lR)
    hikari:
      minimum-idle: 8
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000

mybatis-plus:
  configuration:
    type-aliases-package: com.spider.mp.entity
    map-underscore-to-camel-case: true
    mapper-locations: classpath*:mapper/*.xml
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启SQL语句打印



management:
  endpoint:
    beans:
      enabled: true
    configprops:
      enabled: true
    shutdown:
      enabled: true
  endpoints:
    enabled: true
    enabled-by-default: true
    sensitive: false
    web:
      exposure:
        include: '*'
      base-path: /monitor